name: Clang Build Analyzer

on:
  pull_request:
    branches:
    - master
    types: [opened, reopened, synchronize, ready_for_review]
  schedule:
    # at 10:20 UTC, daily. Time chosen arbitrarily.
    - cron: 20 10 * * *

# Mixing in event_name so that a master push and a workflow dispatch can run at the same time.
concurrency: 
    group: clang_build_analyzer-${{ github.event_name }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install libncursesw5-dev gettext
    - name: Prepare Build Analyzer
      run: |
        cd
        git clone --recursive https://github.com/aras-p/ClangBuildAnalyzer.git buildAnalyzer
        cd buildAnalyzer
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RELEASE ..
        cmake --build . -- -j3
        echo "${PWD}" >> $GITHUB_PATH
    - uses: ammaraskar/gcc-problem-matcher@master
    - name: make
      run: |
        clang++ --version
        ClangBuildAnalyzer --start .
        CLANG=clang++ CXXFLAGS=-ftime-trace make
        ClangBuildAnalyzer --stop . buildAnalysis
    - name: Analyze
      run: ClangBuildAnalyzer --analyze buildAnalysis
    - uses: actions/upload-artifact@v4
      with:
        name: ClangBuildAnalyzer-analysis
        path: buildAnalysis
    - uses: actions/upload-artifact@v4
      with:
        name: ClangBuildAnalyzer-traces
        path: "**/obj/*.json"
